### ISSUE TITLE
tar: Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by TD540** [danylokos/SwiftyTorrent#6]
The extract function doesn't seem to be working for me:

```
$ ./bootstrap.sh
rm: boost.tar.gz: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    10  100    10    0     0     78      0 --:--:-- --:--:-- --:--:--    78
tar: Error opening archive: Unrecognized archive format
Done.
```

Using macOS 12 dev-b2 and Xcode 13 dev-b2

**Comment by danylokos** [comment]
HI, yep, the download link for `boost` library has changed. Just updated it, you can try it again.

**Comment by danylokos** [comment]
Also, i've updated the build steps, don't forget to install Carthage dependencies:

`./carthage.sh bootstrap --platform ios,tvos`
