### ISSUE TITLE
No such module 'MobileVLCKit'

### ISSUE THREAD

**Issue by TD540** [danylokos/SwiftyTorrent#9]
Seeing this import error inside MediaKit > VLC > VLCViewHost

I did the setup exactly as described in your README.md

Both bootstrap.sh scripts successfully ran...

**Comment by danylokos** [comment]
Hi, just pushed an update. Should work now, also there are breaking changes in the latest Xcode 13 beta 4 update, so please update (and re-build the dependencies) if you are using earlier versions.
